### ISSUE TITLE
Tesla Solar Roof (Panels that look like roof tiles)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/roof-garden#1]
https://www.tesla.com/pt_PT/solarroof?redirect=no
![image](https://user-images.githubusercontent.com/194400/31069320-4c6100ba-a75c-11e7-984e-f1cc6c8fef77.png)

@iteles you may want to open this page in your browser _before_ you leave Wifi so you can explain that the roof will _look_ like tiles but will actually be solar. 😉

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/31070781-eeef5304-a761-11e7-8560-d7804ffe9722.png)


![image](https://user-images.githubusercontent.com/194400/31070858-3bb20d30-a762-11e7-8f4f-cef375a745f9.png)

![image](https://user-images.githubusercontent.com/194400/31070933-879cc884-a762-11e7-9ac9-8b2fead573a3.png)

![image](https://user-images.githubusercontent.com/194400/31070967-a5f63810-a762-11e7-8010-bcec9ef55368.png)

![image](https://user-images.githubusercontent.com/194400/31070995-bdc2600e-a762-11e7-8152-3ae266f65944.png)

![image](https://user-images.githubusercontent.com/194400/31071050-eb252d38-a762-11e7-9b80-d81b95ef2e95.png)

![image](https://user-images.githubusercontent.com/194400/31071109-170b8352-a763-11e7-9918-0e8c875cf786.png)

![image](https://user-images.githubusercontent.com/194400/31071169-544b535a-a763-11e7-8b8b-f9cdd5b33d17.png)

**Comment by iteles** [comment]
Has Tesla actually given any indication of price on these yet? I can't seem to find it!

**Comment by nelsonic** [comment]
Elon only said "less than installing a traditional roof and then retrofitting solar panels".
at the moment they only have "reservation" pricing on the PT website.

**Comment by nelsonic** [comment]
On _second_ thoughts, the Tesla Solar Roof is quite a _lot_ more than "traditional" Solar Panels:
[![image](https://user-images.githubusercontent.com/194400/39960578-2689e242-561d-11e8-8898-4ca4771c015a.png)](https://youtu.be/auxp8-gPFtA)
https://youtu.be/auxp8-gPFtA

So, for Braga (Home) we will be using "normal" Solar Panels from https://www.damiasolar.com ☀️ 
see: https://github.com/nelsonic/braga/issues/19
