### ISSUE TITLE
Retractable Glass Roof

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/roof-garden#3]
At present the _draft_ design of the Roof Garden only includes a Static Roof.
![roof-garden-mvp](https://user-images.githubusercontent.com/194400/31070781-eeef5304-a761-11e7-8560-d7804ffe9722.png)
This was deliberate because I don't want the Council to think we are building a fully enclosed "room".
But in _reality_ the roof garden will only add _modest_ value if we can only use it for 7 months a year ...

> What we _need_ is an _amazing_ space that we can use 365 days even when it's _pouring_/_freezing_.

![image](https://user-images.githubusercontent.com/194400/34447521-b349470e-ecdc-11e7-8e51-2ba982bfb6b9.png)
https://youtu.be/2xQVzwLGjV4

![image](https://user-images.githubusercontent.com/194400/34447501-76164fbc-ecdc-11e7-9e6d-2f8930cfc379.png)
https://youtu.be/fuTgoY4Nd4k

I'm going to _re-draw_ the roof to make it a "conservatory" with retractable glass in the middle.

Meanwhile, can you please upload the designs that Francisca submitted to the council? https://github.com/nelsonic/braga/issues/102

**Comment by iteles** [comment]
😱

**Comment by nelsonic** [comment]
sadly no longer relevant as council refused planning permission. 😞
